name: Collate Builds

agent:
  type: Unity::VM
  image: cds-ops/ubuntu-18.04-agent:v1.0.11-765607
  flavor: b1.large

dependencies:
  - .yamato/build_android.yml
  - .yamato/build_linux_x64.yml
  - .yamato/build_linux_x86.yml
  - .yamato/build_osx_classlibs.yml
  - .yamato/build_osx_runtime.yml
  - .yamato/build_win.yml
  - .yamato/build_win_x86.yml
  
commands:
  - .yamato/scripts/collate_builds.sh

triggers:
  branches:
    only:
      - "/.*/"
  recurring:
    - branch: unity-master
      frequency: weekly

artifacts: 
  builds:
    paths:
      - collectedbuilds/builds.7z
  stevedore:
    paths:
      - stevedore/MonoBleedingEdge.7z
      #- stevedore/artifactid.txt
